# Generated by Django 3.0.2 on 2020-01-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('project_start_date', models.DateField(verbose_name='Data de Início')),
                ('project_end_date', models.DateField(verbose_name='Data de Término')),
                ('project_description', models.TextField(verbose_name='Descrição do Projeto')),
                ('project_tecnologies', models.CharField(max_length=500, verbose_name='Tecnologias Utilizadas')),
                ('project_repository', models.CharField(max_length=500, verbose_name='Repositório do Projeto no Github')),
                ('project_site', models.CharField(max_length=500, verbose_name='Site do Projeto')),
                ('project_article', models.CharField(max_length=500, verbose_name='Artigo do Projeto')),
                ('project_colaborators', models.TextField(verbose_name='Colaboradores do Projeto')),
            ],
        ),
    ]
