# Generated by Django 3.0.2 on 2020-01-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_auto_20200129_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborator_name', models.CharField(max_length=200, verbose_name='Coladorador')),
                ('colaborator_repository', models.CharField(max_length=200, verbose_name='Repositório')),
            ],
        ),
    ]
