# Generated by Django 3.0.2 on 2020-01-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_colaborator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_colaborators',
        ),
        migrations.AddField(
            model_name='project',
            name='project_colaborators',
            field=models.ManyToManyField(blank=True, help_text='Colaboradores do Projeto', null=True, to='projetos.Colaborator'),
        ),
    ]
