# Generated by Django 3.0.2 on 2020-01-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_auto_20200129_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_legend', models.CharField(max_length=200, verbose_name='Legenda da Imagem')),
                ('image_url', models.ImageField(upload_to='', verbose_name='Selecione uma imagem')),
                ('image_description', models.TextField(verbose_name='Descrição da Imagem')),
            ],
        ),
        migrations.AlterField(
            model_name='colaborator',
            name='colaborator_repository',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Repositório'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_images',
            field=models.ManyToManyField(blank=True, help_text='Imagens do Projeto', null=True, to='projetos.PrintImages'),
        ),
    ]
