# Generated by Django 3.0.2 on 2020-01-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_auto_20200129_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrintImages',
            new_name='PrintImage',
        ),
        migrations.AddField(
            model_name='project',
            name='project_short_description',
            field=models.CharField(default='', max_length=200, verbose_name='Descrição Breve do Projeto'),
        ),
    ]
